# Generated by Django 5.2.16 on 2026-08-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('announcement', '公告'), ('activity', '活動'), ('exam', '考試'), ('maintenance', '系統維護')], default='announcement', max_length=20)),
                ('tribes', models.JSONField(blank=True, default=list)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('link_url', models.URLField(blank=True, max_length=500)),
                ('is_pinned', models.BooleanField(default=False)),
                ('pin_until', models.DateField(blank=True, null=True)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('unpublish_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待審核'), ('rejected', '已退件'), ('published', '已發布'), ('unpublished', '已下架')], default='draft', max_length=20)),
                ('created_by', models.CharField(max_length=128)),
                ('submitted_by', models.CharField(blank=True, max_length=128)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at', '-pk'],
                'indexes': [models.Index(fields=['status'], name='adminapi_an_status_383591_idx'), models.Index(fields=['category'], name='adminapi_an_categor_0034db_idx')],
            },
        ),
    ]
