# Generated by Django 5.2.16 on 2026-08-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0002_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScheduleCrawlStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_reason', models.TextField(blank=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExamScheduleOverride',
            fields=[
                ('phase', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date', 'phase'],
            },
        ),
    ]
