# Generated by Django 5.2.16 on 2026-08-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0003_examschedulecrawlstatus_examscheduleoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image_url', models.URLField(blank=True, max_length=500)),
                ('hero_link_url', models.CharField(blank=True, max_length=500)),
                ('hero_title_override', models.CharField(blank=True, max_length=100)),
                ('show_news_section', models.BooleanField(default=True)),
                ('show_calendar_section', models.BooleanField(default=True)),
                ('news_display_count', models.PositiveSmallIntegerField(default=6)),
                ('button1_enabled', models.BooleanField(default=True)),
                ('button2_enabled', models.BooleanField(default=True)),
                ('button3_enabled', models.BooleanField(default=True)),
                ('updated_by', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
