# Generated by Django 5.2.16 on 2026-08-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0004_homepageconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_reason', models.TextField(blank=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_imported_count', models.PositiveIntegerField(default=0)),
                ('last_skipped_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='display_date_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='announcement',
            name='external_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='source',
            field=models.CharField(choices=[('admin', '後台建立'), ('crawler', '爬蟲匯入')], default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='source_tag',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['source'], name='adminapi_an_source_7394e5_idx'),
        ),
    ]
