# Generated by Django 5.2.16 on 2026-08-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0005_announcementsyncstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrtConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveSmallIntegerField(default=10)),
                ('alpha0', models.FloatField(default=1.0)),
                ('beta0', models.FloatField(default=1.0)),
                ('default_guess', models.FloatField(default=0.25)),
                ('learning_rate', models.FloatField(default=0.08)),
                ('dq_alpha', models.FloatField(default=0.45)),
                ('dq_beta', models.FloatField(default=0.35)),
                ('dq_gamma', models.FloatField(default=0.2)),
                ('type_aq_word_translate', models.FloatField(default=1.2)),
                ('type_aq_word_match', models.FloatField(default=1.0)),
                ('type_aq_sentence_fill', models.FloatField(default=0.9)),
                ('type_aq_sentence_order', models.FloatField(default=1.1)),
                ('beta1', models.FloatField(default=0.2)),
                ('beta2', models.FloatField(default=0.2)),
                ('beta3', models.FloatField(default=0.2)),
                ('beta4', models.FloatField(default=0.2)),
                ('beta5', models.FloatField(default=0.2)),
                ('updated_by', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tribe', models.CharField(choices=[('tayal', '泰雅語'), ('amis', '阿美語'), ('bunun', '布農語'), ('kavalan', '葛瑪蘭語'), ('paiwan', '排灣語')], max_length=20, unique=True)),
                ('dialect_id', models.PositiveIntegerField()),
                ('display_name', models.CharField(max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tribe'],
            },
        ),
        migrations.CreateModel(
            name='QuizClozePassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待審核'), ('rejected', '已退件'), ('published', '已啟用')], default='draft', max_length=20)),
                ('created_by', models.CharField(max_length=128)),
                ('submitted_by', models.CharField(blank=True, max_length=128)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tribe', models.CharField(choices=[('tayal', '泰雅語'), ('amis', '阿美語'), ('bunun', '布農語'), ('kavalan', '葛瑪蘭語'), ('paiwan', '排灣語')], max_length=20)),
                ('passage_foreign', models.TextField()),
                ('passage_chinese', models.TextField()),
                ('blanks', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['tribe', 'status'], name='adminapi_qu_tribe_b6d81e_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizSituationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待審核'), ('rejected', '已退件'), ('published', '已啟用')], default='draft', max_length=20)),
                ('created_by', models.CharField(max_length=128)),
                ('submitted_by', models.CharField(blank=True, max_length=128)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tribe', models.CharField(choices=[('tayal', '泰雅語'), ('amis', '阿美語'), ('bunun', '布農語'), ('kavalan', '葛瑪蘭語'), ('paiwan', '排灣語')], max_length=20)),
                ('scenario_chinese', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('answer', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['tribe', 'status'], name='adminapi_qu_tribe_1f7f01_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizVocabItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待審核'), ('rejected', '已退件'), ('published', '已啟用')], default='draft', max_length=20)),
                ('created_by', models.CharField(max_length=128)),
                ('submitted_by', models.CharField(blank=True, max_length=128)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tribe', models.CharField(choices=[('tayal', '泰雅語'), ('amis', '阿美語'), ('bunun', '布農語'), ('kavalan', '葛瑪蘭語'), ('paiwan', '排灣語')], max_length=20)),
                ('category', models.CharField(choices=[('noun', '名詞'), ('verb', '動詞'), ('time', '時間'), ('function', '功能詞'), ('kin', '親屬稱謂')], max_length=20)),
                ('foreign_word', models.CharField(max_length=100)),
                ('chinese_gloss', models.CharField(max_length=100)),
                ('audio_file_id', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['tribe', 'category', 'status'], name='adminapi_qu_tribe_9d0ced_idx')],
            },
        ),
    ]
