# Generated by Django 5.2.16 on 2026-08-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0006_irtconfig_quizsourceconfig_quizclozepassage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizChoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待審核'), ('rejected', '已退件'), ('published', '已啟用')], default='draft', max_length=20)),
                ('created_by', models.CharField(max_length=128)),
                ('submitted_by', models.CharField(blank=True, max_length=128)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tribe', models.CharField(choices=[('tayal', '泰雅語'), ('amis', '阿美語'), ('bunun', '布農語'), ('kavalan', '葛瑪蘭語'), ('paiwan', '排灣語')], max_length=20)),
                ('question_ab', models.CharField(max_length=300)),
                ('question_ch', models.CharField(max_length=300)),
                ('image_a_url', models.URLField(max_length=500)),
                ('image_b_url', models.URLField(max_length=500)),
                ('image_c_url', models.URLField(max_length=500)),
                ('answer', models.PositiveSmallIntegerField()),
                ('origin_key', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['tribe', 'status'], name='adminapi_qu_tribe_eef8cf_idx')],
                'constraints': [models.UniqueConstraint(fields=('tribe', 'origin_key'), name='unique_choice_tribe_origin_key')],
            },
        ),
        migrations.CreateModel(
            name='QuizTrueFalseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待審核'), ('rejected', '已退件'), ('published', '已啟用')], default='draft', max_length=20)),
                ('created_by', models.CharField(max_length=128)),
                ('submitted_by', models.CharField(blank=True, max_length=128)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tribe', models.CharField(choices=[('tayal', '泰雅語'), ('amis', '阿美語'), ('bunun', '布農語'), ('kavalan', '葛瑪蘭語'), ('paiwan', '排灣語')], max_length=20)),
                ('question_ab', models.CharField(max_length=300)),
                ('question_ch', models.CharField(max_length=300)),
                ('audio_url', models.URLField(max_length=500)),
                ('image_url', models.URLField(max_length=500)),
                ('answer', models.PositiveSmallIntegerField(choices=[(1, 'O（符合）'), (2, 'X（不符合）')])),
                ('origin_key', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['tribe', 'status'], name='adminapi_qu_tribe_f3ec13_idx')],
                'constraints': [models.UniqueConstraint(fields=('tribe', 'origin_key'), name='unique_true_false_tribe_origin_key')],
            },
        ),
    ]
