# Generated by Django 5.2.16 on 2026-08-03 11:11

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0007_quizchoiceitem_quiztruefalseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.PositiveIntegerField()),
                ('payload', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('pending_review', '待審核'), ('approved', '已核准'), ('rejected', '已退件')], default='pending_review', max_length=20)),
                ('submitted_by', models.CharField(max_length=128)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-submitted_at', '-pk'],
                'indexes': [models.Index(fields=['target_type', 'target_id', 'status'], name='adminapi_pe_target__a880a1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending_review')), fields=('target_type', 'target_id'), name='unique_pending_revision_per_target')],
            },
        ),
    ]
