# Generated by Django 5.2.16 on 2026-08-05 09:53

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0008_pendingrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('tribe', models.CharField(max_length=20)),
                ('payload', models.JSONField()),
                ('report', models.JSONField(blank=True, default=dict)),
                ('preflight_hash', models.CharField(blank=True, max_length=71)),
                ('status', models.CharField(choices=[('uploaded', '已上傳'), ('validated', '已預檢'), ('pending_review', '待審核'), ('applied', '已套用'), ('applied_with_errors', '已套用（部分失敗）'), ('rejected', '已退件')], default='uploaded', max_length=24)),
                ('new_count', models.PositiveIntegerField(default=0)),
                ('update_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('applied_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.CharField(max_length=128)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('applied_by', models.CharField(blank=True, max_length=128)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at', '-pk'],
                'indexes': [models.Index(fields=['status', 'uploaded_at'], name='adminapi_di_status_166521_idx')],
            },
        ),
        migrations.CreateModel(
            name='DictionaryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_kind', models.CharField(choices=[('word', '詞條'), ('grammar_section', '文法章節')], max_length=32)),
                ('target_id', models.CharField(blank=True, max_length=128)),
                ('tribe', models.CharField(blank=True, max_length=20)),
                ('operation', models.CharField(choices=[('create', '新建'), ('update', '修改'), ('delete', '刪除')], max_length=16)),
                ('payload', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('base_hash', models.CharField(blank=True, max_length=71)),
                ('title_cache', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待審核'), ('approved', '已核准'), ('rejected', '已退件'), ('failed', '套用失敗')], default='draft', max_length=20)),
                ('submitted_by', models.CharField(blank=True, max_length=128)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('apply_error', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at', '-pk'],
                'indexes': [models.Index(fields=['target_kind', 'target_id', 'status'], name='adminapi_di_target__c5718a_idx'), models.Index(fields=['status', 'submitted_at'], name='adminapi_di_status_c8024d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending_review'), models.Q(('target_id', ''), _negated=True)), fields=('target_kind', 'target_id'), name='unique_pending_dictionary_revision_per_target')],
            },
        ),
    ]
