# Generated by Django 5.2.16 on 2026-08-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0009_dictionaryimportjob_dictionaryrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('uid', models.CharField(blank=True, max_length=128)),
                ('tribe', models.CharField(blank=True, max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='adminapi_us_event_t_880b9f_idx'), models.Index(fields=['uid', 'created_at'], name='adminapi_us_uid_9958e6_idx')],
            },
        ),
    ]
