# Generated by Django 5.2.16 on 2026-08-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0010_usageevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrosswordTayalWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('meaning', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_by', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening_questions_per_round', models.PositiveSmallIntegerField(default=10)),
                ('listening_options_per_question', models.PositiveSmallIntegerField(default=4)),
                ('sentence_questions_per_round', models.PositiveSmallIntegerField(default=5)),
                ('sentence_options_per_question', models.PositiveSmallIntegerField(default=4)),
                ('pronunciation_max_audio_mb', models.PositiveSmallIntegerField(default=10)),
                ('pronunciation_excellent_threshold', models.PositiveSmallIntegerField(default=80)),
                ('pronunciation_good_threshold', models.PositiveSmallIntegerField(default=60)),
                ('pronunciation_fair_threshold', models.PositiveSmallIntegerField(default=40)),
                ('pronunciation_pass_threshold', models.PositiveSmallIntegerField(default=70)),
                ('crossword_grid_size', models.PositiveSmallIntegerField(default=13)),
                ('crossword_min_word_length', models.PositiveSmallIntegerField(default=4)),
                ('crossword_max_word_length', models.PositiveSmallIntegerField(default=10)),
                ('crossword_words_per_round', models.PositiveSmallIntegerField(default=30)),
                ('crossword_compute_time_limit_seconds', models.PositiveSmallIntegerField(default=2)),
                ('updated_by', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RateLimitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('backend', models.CharField(choices=[('django', 'Django'), ('fastapi', 'FastAPI')], max_length=10)),
                ('rate', models.CharField(max_length=20)),
                ('default_rate', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['backend', 'key'],
                'indexes': [models.Index(fields=['backend'], name='adminapi_ra_backend_120b4d_idx')],
            },
        ),
    ]
