# Generated by Django 5.2.16 on 2026-08-11 09:59
#
# 這支 migration 沒有搭配資料匯出/保留步驟就直接刪表——一般情況下這是
# 該補的事（DeleteModel 掉一張後台可編輯的內容表，理論上會悄悄丟掉任何
# admin 事後編輯過的資料）。這裡刻意不補的原因是專案歷史紀錄，不是「反正
# 有 git 就不用做資料遷移」的通用主張：這張表從建立（commit 6205017）到
# 這支 migration 之間只隔了約一天、始終停留在本機開發分支、從未部署，且
# 期間唯一的管理者（本人）已明確決定放棄泰雅語專屬詞庫、改成跟其他 4 個
# 族語一樣即時查辭典——沒有任何真實的後台編輯內容存在。原始種子的 20 筆
# 資料本身仍完整保留在 commit 6205017 的
# adminapi/management/commands/seed_crossword_tayal_words.py 歷史版本裡。
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0011_crosswordtayalword_featureflag_gameconfig_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrosswordTayalWord',
        ),
    ]
