# Generated by Django 5.2.16 on 2026-08-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0012_delete_crosswordtayalword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryimportjob',
            name='status',
            field=models.CharField(choices=[('uploaded', '已上傳'), ('validated', '已預檢'), ('pending_review', '待審核'), ('applying', '套用中'), ('applied', '已套用'), ('applied_with_errors', '已套用（部分失敗）'), ('rejected', '已退件')], default='uploaded', max_length=24),
        ),
    ]
