# Generated by Django 5.2.16 on 2026-10-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0013_alter_dictionaryimportjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResearchConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(max_length=64, unique=True)),
                ('consent_version', models.CharField(max_length=40)),
                ('granted_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSkillEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(max_length=64)),
                ('nonce', models.CharField(max_length=40)),
                ('occurred_at', models.DateTimeField()),
                ('tribe', models.CharField(max_length=20)),
                ('question_type', models.CharField(max_length=20)),
                ('target_rule_id', models.CharField(blank=True, max_length=200)),
                ('selected_rule_id', models.CharField(blank=True, max_length=200)),
                ('diagnosis_status', models.CharField(max_length=20)),
                ('error_type', models.CharField(blank=True, max_length=20)),
                ('correct', models.BooleanField()),
                ('probe', models.BooleanField()),
                ('seconds_bucket', models.SmallIntegerField()),
                ('p_before', models.FloatField(blank=True, null=True)),
                ('p_after', models.FloatField(blank=True, null=True)),
                ('pred_skill', models.FloatField(blank=True, null=True)),
                ('pred_ability', models.FloatField(blank=True, null=True)),
                ('ability_before', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(max_length=32)),
                ('kit_version', models.CharField(blank=True, max_length=40)),
                ('selection_policy', models.CharField(max_length=40)),
                ('consent_version', models.CharField(max_length=40)),
            ],
            options={
                'indexes': [models.Index(fields=['pseudonym', 'id'], name='adminapi_qu_pseudon_4a2977_idx'), models.Index(fields=['tribe', 'occurred_at'], name='adminapi_qu_tribe_b736a7_idx')],
                'constraints': [models.UniqueConstraint(fields=('pseudonym', 'nonce'), name='uniq_quizskillevent_pseudonym_nonce')],
            },
        ),
    ]
