# Generated by Django 5.2.16 on 2026-10-07 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0014_quizresearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('tribe', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=20)),
                ('form', models.CharField(max_length=200)),
                ('proposal', models.JSONField(blank=True, null=True)),
                ('created_by_uid', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tribe', 'kind', 'created_at', 'id'], name='adminapi_ve_tribe_29fc5b_idx'), models.Index(fields=['kind', 'created_at', 'id'], name='adminapi_ve_kind_784870_idx'), models.Index(fields=['created_at', 'id'], name='adminapi_ve_created_9c7b5a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ('unmatched_form', 'morph_analysis'))), name='verificationitem_kind_valid')],
            },
        ),
        migrations.CreateModel(
            name='VerificationObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('report_version', models.PositiveSmallIntegerField()),
                ('report_label', models.CharField(max_length=40)),
                ('occurrence_count', models.PositiveIntegerField()),
                ('sentence_count', models.PositiveIntegerField()),
                ('list_size', models.PositiveIntegerField()),
                ('observed_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='adminapi.verificationitem')),
            ],
            options={
                'ordering': ['-observed_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('item', 'source', 'report_label'), name='uniq_verificationobservation'), models.CheckConstraint(condition=models.Q(('source__in', ('coverage', 'benchmark'))), name='verificationobservation_source_valid'), models.CheckConstraint(condition=models.Q(('report_version__gt', 0), ('list_size__gt', 0)), name='verificationobservation_positive'), models.CheckConstraint(condition=models.Q(('report_label', ''), _negated=True), name='verificationobservation_label_nonempty'), models.CheckConstraint(condition=models.Q(('sentence_count__lte', models.F('occurrence_count'))), name='verificationobservation_counts')],
            },
        ),
        migrations.CreateModel(
            name='VerificationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_type', models.CharField(max_length=10)),
                ('reviewer_subject', models.CharField(max_length=128)),
                ('reviewer_label', models.CharField(max_length=64)),
                ('entered_by_uid', models.CharField(max_length=128)),
                ('verdict', models.CharField(max_length=10)),
                ('correction', models.CharField(blank=True, max_length=200)),
                ('correction_norm', models.CharField(blank=True, max_length=600)),
                ('dialect', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='adminapi.verificationitem')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['item', 'verdict'], name='adminapi_ve_item_id_b2ce84_idx'), models.Index(fields=['reviewer_type', 'reviewer_subject'], name='adminapi_ve_reviewe_1b1bb6_idx')],
                'constraints': [models.UniqueConstraint(fields=('item', 'reviewer_type', 'reviewer_subject'), name='uniq_verificationreview_reviewer'), models.CheckConstraint(condition=models.Q(('verdict__in', ('agree', 'disagree', 'uncertain'))), name='verificationreview_verdict_valid'), models.CheckConstraint(condition=models.Q(('reviewer_type__in', ('staff', 'external'))), name='verificationreview_type_valid'), models.CheckConstraint(condition=models.Q(('reviewer_subject', ''), _negated=True), name='verificationreview_subject_nonempty')],
            },
        ),
    ]
