# Generated by Django 5.2.16 on 2026-10-07 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0015_verification_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tribe', models.CharField(max_length=20)),
                ('dialect_label', models.CharField(max_length=20)),
                ('entry_code', models.CharField(max_length=20)),
                ('seq', models.PositiveIntegerField()),
                ('level', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=60)),
                ('zh', models.CharField(max_length=200)),
                ('raw_cell', models.CharField(max_length=400)),
                ('note', models.CharField(blank=True, max_length=400)),
                ('source_label', models.CharField(max_length=60)),
                ('source_sha256', models.CharField(max_length=64)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tribe', 'dialect_label', 'seq'],
                'indexes': [models.Index(fields=['tribe', 'dialect_label', 'seq'], name='adminapi_wo_tribe_fd5a13_idx')],
                'constraints': [models.UniqueConstraint(fields=('tribe', 'dialect_label', 'entry_code'), name='wordlistentry_code_unique')],
            },
        ),
        migrations.CreateModel(
            name='WordlistForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_index', models.PositiveSmallIntegerField()),
                ('form', models.CharField(max_length=200)),
                ('match_class', models.CharField(max_length=24)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('sense_check', models.CharField(blank=True, max_length=16)),
                ('candidate_fingerprint', models.CharField(blank=True, max_length=64)),
                ('candidates_truncated', models.BooleanField(default=False)),
                ('snapshot_at', models.DateTimeField()),
                ('decision', models.CharField(blank=True, default='', max_length=10)),
                ('decided_word_id', models.CharField(blank=True, max_length=64)),
                ('decided_by_uid', models.CharField(blank=True, max_length=128)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_basis', models.CharField(blank=True, max_length=64)),
                ('decision_stale', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='adminapi.wordlistentry')),
            ],
            options={
                'ordering': ['entry_id', 'split_index'],
            },
        ),
        migrations.CreateModel(
            name='WordlistApplyJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=36)),
                ('action', models.CharField(max_length=20)),
                ('tribe', models.CharField(max_length=20)),
                ('word_id', models.CharField(max_length=64)),
                ('before_hash', models.CharField(max_length=80)),
                ('after_hash', models.CharField(blank=True, max_length=80)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('actor', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal', to='adminapi.wordlistform')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='wordlistform',
            index=models.Index(fields=['match_class', 'decision'], name='adminapi_wo_match_c_7e88ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='wordlistform',
            constraint=models.UniqueConstraint(fields=('entry', 'split_index'), name='wordlistform_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='wordlistform',
            constraint=models.CheckConstraint(condition=models.Q(('match_class__in', ('skip_placeholder', 'manual_multiple', 'same_dialect_unique', 'unknown_dialect_unique', 'cross_dialect_unique', 'manual_near_form', 'new'))), name='wordlistform_match_class_valid'),
        ),
        migrations.AddConstraint(
            model_name='wordlistform',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ('', 'accept', 'reject', 'defer'))), name='wordlistform_decision_valid'),
        ),
        migrations.AddConstraint(
            model_name='wordlistform',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'accept'), models.Q(('decided_word_id', ''), _negated=True)), models.Q(models.Q(('decision', 'accept'), _negated=True), ('decided_word_id', '')), _connector='OR'), name='wordlistform_accept_needs_word'),
        ),
        migrations.AddConstraint(
            model_name='wordlistform',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', ''), ('decided_by_uid', ''), ('decided_at__isnull', True), ('decision_basis', ''), ('decision_stale', False)), models.Q(models.Q(('decision', ''), _negated=True), models.Q(('decided_by_uid', ''), _negated=True), ('decided_at__isnull', False), models.Q(('decision_basis', ''), _negated=True)), _connector='OR'), name='wordlistform_decision_metadata'),
        ),
        migrations.AddIndex(
            model_name='wordlistapplyjournal',
            index=models.Index(fields=['status', 'batch_id'], name='adminapi_wo_status_167d23_idx'),
        ),
        migrations.AddConstraint(
            model_name='wordlistapplyjournal',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ('append_source', 'append_explanation'))), name='wordlistjournal_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='wordlistapplyjournal',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'applied', 'reverted'))), name='wordlistjournal_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='wordlistapplyjournal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'pending'), ('after_hash', ''), ('applied_at__isnull', True), ('reverted_at__isnull', True)), models.Q(('status', 'applied'), models.Q(('after_hash', ''), _negated=True), ('applied_at__isnull', False), ('reverted_at__isnull', True)), models.Q(('status', 'reverted'), models.Q(('after_hash', ''), _negated=True), ('applied_at__isnull', False), ('reverted_at__isnull', False)), _connector='OR'), name='wordlistjournal_status_fields'),
        ),
        migrations.AddConstraint(
            model_name='wordlistapplyjournal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'reverted'), _negated=True), fields=('form', 'action'), name='wordlistjournal_one_live_per_action'),
        ),
    ]
