# Generated by Django 5.2.16 on 2026-10-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0016_wordlist_mapping'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wordlistapplyjournal',
            name='wordlistjournal_action_valid',
        ),
        migrations.RemoveConstraint(
            model_name='wordlistform',
            name='wordlistform_decision_valid',
        ),
        migrations.RemoveConstraint(
            model_name='wordlistform',
            name='wordlistform_accept_needs_word',
        ),
        migrations.AddConstraint(
            model_name='wordlistapplyjournal',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ('append_source', 'append_explanation', 'create_word'))), name='wordlistjournal_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='wordlistform',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ('', 'accept', 'reject', 'defer', 'create'))), name='wordlistform_decision_valid'),
        ),
        migrations.AddConstraint(
            model_name='wordlistform',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision__in', ['accept', 'create']), models.Q(('decided_word_id', ''), _negated=True)), models.Q(models.Q(('decision__in', ['accept', 'create']), _negated=True), ('decided_word_id', '')), _connector='OR'), name='wordlistform_accept_needs_word'),
        ),
    ]
