"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

from config.logging import get_logging_config
from config.auth_flags import auth_dev_bypass
from config.debug_flag import is_debug
from config.sentry_init import init_sentry
from config.cors import get_allowed_origins

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError(
        "DJANGO_SECRET_KEY 未設定，請在 .env 填入隨機金鑰。\n"
        "產生方式：python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = is_debug()

# 是否略過 Firebase token 驗證（僅限本機開發）。互鎖判斷邏輯與 FastAPI 端共用
# （見 config/auth_flags.py），避免兩邊各自實作、修一處忘了改另一處。
AUTH_DEV_BYPASS = auth_dev_bypass()


# 正式環境安全設定（manage.py check --deploy 的 W004/W008/W012/W016）。用 not DEBUG
# 而非另開環境變數：本機開發本來就走 HTTP，強制 SSL redirect／secure cookie 會直接
# 讓本機登入失敗，這些設定只在「非 DEBUG＝視為正式環境」時才需要生效。
# SECURE_PROXY_SSL_HEADER 例外，兩種環境都設定：Render/Cloud Run 對外都是 HTTPS，
# 但反向代理到 Django process 這一段是 HTTP，Django 原生的 request.is_secure() 會誤判
# 成不安全連線，導致 SECURE_SSL_REDIRECT 陷入重導迴圈、secure cookie 也不會被送出。
# 這兩個平台都會在自己的邊緣層蓋掉用戶端送來的 X-Forwarded-Proto，不會讓外部請求
# 偽造這個標頭，才能放心依它判斷；本機開發沒有反向代理，不會有這個標頭，不受影響。
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # 先從 1 小時開始（Django 官方文件建議的做法）：確認正式環境 HTTPS 運作正常、
    # 沒有把自己鎖在外面之後，再逐步拉長這個數字。
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
# Render 會自動注入 RENDER_EXTERNAL_HOSTNAME；其他平台（Cloud Run 等）沒有這個
# 環境變數，改用 DJANGO_ALLOWED_HOSTS（逗號分隔）手動指定，兩者可並存。
_render_host = os.getenv("RENDER_EXTERNAL_HOSTNAME")
if _render_host:
    ALLOWED_HOSTS.append(_render_host)
_extra_hosts = os.getenv("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS += [h.strip() for h in _extra_hosts.split(",") if h.strip()]

APPEND_SLASH = False
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'crawler.apps.CrawlerConfig',
    'AIModel.apps.AimodelConfig',
    'rest_framework',
    'corsheaders',
    "core",
    'CrosswordPuzzle.apps.CrosswordpuzzleConfig',
    'drf_yasg',
    'adminapi.apps.AdminapiConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    # 緊接在 SecurityMiddleware 之後（WhiteNoise 官方要求的順序）。專案沒有另外的
    # nginx/CDN 幫 Django 服務 static/，STATIC_ROOT 之前又是註解掉的狀態，
    # collectstatic 沒有輸出目的地，正式環境等於沒有任何機制能提供 admin／DRF／
    # Swagger UI 需要的 CSS/JS，畫面樣式會跑掉。WhiteNoise 讓 Django process
    # 自己把 collectstatic 的輸出檔案送出去，不需要額外起一個靜態檔伺服器。
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# 讀取/預設值邏輯見 config/cors.py（跟 fastAPI/main.py 共用同一份，
# 避免兩邊各自維護一份一模一樣的 os.getenv(key) or default 寫法）。
CORS_ALLOWED_ORIGINS = get_allowed_origins()
# CSRF
# 正式部署的網域跟 ALLOWED_HOSTS 一樣改讀環境變數（逗號分隔），不再寫死單一
# 平台的網址——先前寫死一個 Cloud Run URL，但 ALLOWED_HOSTS 只認 Render 的
# 環境變數，兩者對不上，換一個部署環境（甚至只是換 Cloud Run 專案/區域）就要
# 改程式碼才能生效。本機開發預設值維持不變。
_raw_csrf_origins = os.getenv("CSRF_TRUSTED_ORIGINS") or "http://127.0.0.1:8000,http://127.0.0.1:8001,http://localhost:5173"
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _raw_csrf_origins.split(",") if o.strip()]
#字元
DEFAULT_CHARSET = 'utf-8'


ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        #"DIRS": [BASE_DIR.parent / "dist"],
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
WSGI_APPLICATION = "core.wsgi.application"
ASGI_APPLICATION = "core.asgi.application"

# Database
# 讀 DATABASE_URL 環境變數（正式環境指向 PostgreSQL），沒設定時退回 SQLite——
# 本機開發、CI 完全不受影響，維持原本零設定即可跑的行為。後台管理系統的
# 讀寫（公告、稽核日誌等）需要能撐過容器重啟/重新部署，Render/Cloud Run
# 的檔案系統是暫時性的，SQLite 檔案在那些平台上撐不住這個需求，這也是
# 這個專案原本的 README 就已經寫著「生產環境請切換至 PostgreSQL」的原因。
_database_url = os.getenv("DATABASE_URL")
if _database_url:
    DATABASES = {
        "default": dj_database_url.parse(
            _database_url,
            conn_max_age=600,
            # Render/Cloud Run 這類受管平台的 Postgres 連線一律要求 TLS；
            # ssl_require=True 只在有設定 DATABASE_URL（代表正式/類正式環境）
            # 時生效，本機開發走 SQLite 分支完全不受影響。
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

#FRONTEND_BUILD_DIR = BASE_DIR.parent / "dist"

TEMPLATES[0]["DIRS"] = [BASE_DIR/"dist"]
#TEMPLATES[0]["DIRS"] = [FRONTEND_BUILD_DIR]
#STATICFILES_DIRS = [FRONTEND_BUILD_DIR / "assets"]

STATIC_URL = "static/"
#STATIC_URL = "/assets/"
# collectstatic 的輸出目的地；WhiteNoise（見上方 MIDDLEWARE）在正式環境從這裡讀檔
# 送出去。部署流程需要在啟動前執行一次 `python manage.py collectstatic --noinput`。
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# 限流（AIModel/CrosswordPuzzle/crawler 的 is_ratelimited）計數存放位置。
# 沒設定 REDIS_URL 時沿用 Django 預設的 LocMemCache：僅限單一 process 內有效，
# gunicorn 開多個 worker 時，因為每個 worker 各自一份記憶體、互不共享計數，
# 同一個限流門檻（例如「每分鐘 30 次」）會被 worker 數量乘倍放大（4 個 worker
# 實際上變成每分鐘 120 次）。設定 REDIS_URL 後，所有 worker 共用同一份計數，
# 門檻才會如實生效；本機開發／未設定 Redis 時維持原本行為，不強制要求 Redis。
_redis_url = os.getenv("REDIS_URL")
if _redis_url:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": _redis_url,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 結構化 JSON log + rotation（見 config/logging.py），FastAPI 端共用同一套設定
LOGGING = get_logging_config("django.log")

# 錯誤追蹤／告警（選用，設定 SENTRY_DSN 後才會啟用）。原本沒有接任何錯誤追蹤
# 服務，結構化 log 只寫在容器本機檔案，Cloud Run/Render 重啟就消失，出錯（含
# 呼叫 Google Vision、GitHub Models 這些按用量計費的外部服務失敗）不會有人
# 主動被通知。未設定 SENTRY_DSN 時完全不影響現有行為。共用邏輯見
# config/sentry_init.py（FastAPI 端 fastAPI/main.py 呼叫同一個函式）。
def _django_sentry_integrations():
    from sentry_sdk.integrations.django import DjangoIntegration
    return [DjangoIntegration()]


init_sentry(_django_sentry_integrations)