"""P5 數據分析：FastAPI 端直接寫入 `UsageEvent` 的輕量機制。

見 backend/adminapi/models.py 的 `UsageEvent` model 說明——這是 FastAPI
第一次寫入 Django migration 管理的 Postgres 表，跟既有 dictionary_db
（Django 的 adminapi 用原生 SQLAlchemy session 直接寫進一個不是它自己
migration 管理的 Postgres 表）是同一種「兩個服務共用同一個 Postgres
執行個體、各自用最適合自己框架的方式直接存取」精神，只是方向相反。

刻意不用 ORM（不 import Django 的 model 定義，也不建 SQLAlchemy
declarative model）——這裡只需要對一個扁平表做單筆 INSERT，不需要關聯或
查詢能力，用 SQLAlchemy Core 的 `Table`/`insert()` 就足夠，且完全不依賴
Django 的程式碼，符合兩個服務本來就是獨立部署單元的既有分工。**這張表的
欄位一旦異動，這裡手動組的 `Table` 定義要記得同步更新**，兩邊沒有共用的
schema 定義來源。

`record_event()` 是 fire-and-forget：任何失敗（連線失敗、DATABASE_URL
沒設定、表結構對不上）只記 log，絕不讓呼叫端（例如辭典搜尋端點）的回應
失敗或變慢太多——分析事件遺漏不該影響任何使用者可見的功能，這是全專案
「輕量事件記錄」一貫的定位（見規劃文件 P5 §1）。
"""
import logging
import os
from datetime import datetime, timezone as dt_timezone

from sqlalchemy import Column, DateTime, MetaData, String, Table, create_engine, insert
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.exc import SQLAlchemyError

logger = logging.getLogger(__name__)

_database_url = os.getenv("DATABASE_URL")
# Render/Heroku 慣例給 postgres://，SQLAlchemy 2.x 只認得 postgresql://——
# 跟 dictionary_db/connect.py 同一個理由，這裡要自己正規化一次。
if _database_url and _database_url.startswith("postgres://"):
    _database_url = "postgresql://" + _database_url[len("postgres://"):]

# DATABASE_URL 沒設定時（本機開發沒接 Postgres，或這個部署從未跑過 P0 的
# Postgres 遷移）_engine 留 None——record_event() 靜默跳過整個寫入，這不是
# 硬性依賴，不影響 FastAPI 其餘功能運作。
_engine = None
if _database_url:
    _engine = create_engine(
        _database_url,
        pool_size=2, max_overflow=3, pool_timeout=5,
        pool_pre_ping=True, pool_recycle=1800,
    )

_metadata = MetaData()
# 對應 backend/adminapi/models.py 的 UsageEvent + migrations/0010_usageevent.py
# ——欄位名稱/型別必須跟 Django migration 建出來的表結構一致，id 是
# Postgres IDENTITY 欄位（GENERATED BY DEFAULT AS IDENTITY），不需要在
# INSERT 裡指定。
_usage_event_table = Table(
    "adminapi_usageevent",
    _metadata,
    Column("event_type", String(40)),
    Column("uid", String(128)),
    Column("tribe", String(20)),
    Column("payload", JSONB),
    Column("created_at", DateTime(timezone=True)),
)


def record_event(event_type: str, uid: str = "", tribe: str = "", payload: dict | None = None) -> None:
    """fire-and-forget 寫入一筆使用事件。呼叫端不需要（也不應該）處理任何
    例外——失敗只會被記錄，函式本身永遠正常返回。"""
    if _engine is None:
        return
    try:
        with _engine.begin() as conn:
            conn.execute(
                insert(_usage_event_table).values(
                    event_type=event_type,
                    uid=uid or "",
                    tribe=tribe or "",
                    payload=payload or {},
                    created_at=datetime.now(dt_timezone.utc),
                )
            )
    except SQLAlchemyError:
        logger.warning("使用事件記錄失敗（不影響主要功能）：event_type=%s", event_type, exc_info=True)
    except Exception:
        # 保守起見連非 SQLAlchemy 例外也一併吞掉——這個函式的唯一存在意義
        # 是「絕不能讓分析事件記錄拖垮呼叫端的主要功能」。
        logger.warning("使用事件記錄發生非預期例外（不影響主要功能）：event_type=%s", event_type, exc_info=True)
